### ISSUE TITLE
v0.3.0 gives errors regarding the from_bytes handling of the response

### ISSUE THREAD

**Issue by CHgsd** [Ape/samsungctl#11]
The from_bytes handling of the response is producing errors as follows:
```
$ samsungctl
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 9, in <module>
    load_entry_point('samsungctl===0.3.0-git', 'console_scripts', 'samsungctl')()
  File "build/bdist.linux-x86_64/egg/samsungctl/__main__.py", line 101, in main
  File "build/bdist.linux-x86_64/egg/samsungctl/remote.py", line 27, in __init__
  File "build/bdist.linux-x86_64/egg/samsungctl/remote.py", line 51, in _read_response
AttributeError: type object 'int' has no attribute 'from_bytes'
```

While I found this potentially relevant suggestion, I did not pursue any further:
https://stackoverflow.com/questions/28210333/python-nonetype-object-has-no-attribute-from-bytes

If these are all user error on my part, my apologies! I did my best to troubleshoot through these.

Thank you!

**Comment by Ape** [comment]
This should be working with Python 3. Please report if it still occurs.
