### ISSUE TITLE
No success with MU6400 - UnhandledResponse

### ISSUE THREAD

**Issue by rosscullen** [Ape/samsungctl#123]
Hi there,
No joy using Samsung MU6400 TV (Tizen 3).
I can access http://192.168.*.*:8001/api/v2/ with response:

`{"device":{"FrameTVSupport":"false","GamePadSupport":"true","ImeSyncedSupport":"true","OS":"Tizen","TokenAuthSupport":"true","VoiceSupport":"true","countryCode":"IE","description":"Samsung DTV RCR","developerIP":"0.0.0.0","developerMode":"0","duid":"uuid:659a783e-234c-4d22-9adc-8adc96ae377d","firmwareVersion":"Unknown","id":"uuid:659a783e-234c-4d22-9adc-8adc96ae377d","ip":"192.168.x.x","model":"17_KANTM_UHD_BASIC","modelName":"UE55MU6400","name":"[TV] Samsung TV","networkType":"wired","resolution":"3840x2160","smartHubAgreement":"true","type":"Samsung SmartTV","udn":"uuid:659a783e-234c-4d22-9adc-8adc96ae377d","wifiMac":"9c:8c:6e:88:1e:8d"},"id":"uuid:659a783e-234c-4d22-9adc-8adc96ae377d","isSupport":"{\"DMP_DRM_PLAYREADY\":\"false\",\"DMP_DRM_WIDEVINE\":\"false\",\"DMP_available\":\"true\",\"EDEN_available\":\"true\",\"FrameTVSupport\":\"false\",\"ImeSyncedSupport\":\"true\",\"TokenAuthSupport\":\"true\",\"remote_available\":\"true\",\"remote_fourDirections\":\"true\",\"remote_touchPad\":\"true\",\"remote_voiceControl\":\"true\"}\n","name":"[TV] Samsung TV","remote":"1.0","type":"Samsung SmartTV","uri":"http://192.168.x.x:8001/api/v2/","version":"2.0.25"}`

When I run the command, I get the following:
```
python` -m samsungctl --host 192.168.x.x --port 8001             
Traceback (most recent call last):                                              
  File "/usr/local/lib/python3.8/runpy.py", line 192, in _run_module_as_main    
    return _run_code(code, main_globals, None,                                  
  File "/usr/local/lib/python3.8/runpy.py", line 85, in _run_code               
    exec(code, run_globals)                                                     
  File "/usr/local/lib/python3.8/site-packages/samsungctl/__main__.py", line 133
, in <module>                                                                   
    main()                                                                      
  File "/usr/local/lib/python3.8/site-packages/samsungctl/__main__.py", line 110
, in main                                                                       
    with Remote(config) as remote:                                              
  File "/usr/local/lib/python3.8/site-packages/samsungctl/remote.py", line 9, in
 __init__                                                                       
    self.remote = RemoteLegacy(config)                                          
  File "/usr/local/lib/python3.8/site-packages/samsungctl/remote_legacy.py", lin
e 32, in __init__                                                               
    self._read_response(True)                                                   
  File "/usr/local/lib/python3.8/site-packages/samsungctl/remote_legacy.py", lin
e 95, in _read_response                                                         
    raise exceptions.UnhandledResponse(response)                                
samsungctl.exceptions.UnhandledResponse: b'tml><body><h1>403</h1></body></html>'

```
TV using latest 1270 firmware.                                                           
Would appreciate any help! Sorry is this is a known issue. Thanks!

**Comment by rosscullen** [comment]
No response, closing.
