### ISSUE TITLE
[REQUEST] Support for notifications

### ISSUE THREAD

**Issue by kylerw** [Ape/samsungctl#37]
Would be great to be able to send notifications to the TV

**Comment by AnderssonPeter** [comment]
This would be awesome but the question is if the api that the tv's provides supports this functionality.

**Comment by tuxuser** [comment]
Tested on B-series successfully:

```py
"""
Send notifications to Samsung TV via uPnP MessageBox service

Tested on B-Series TV

by tuxuser (2018/07/21) https://github.com/tuxuser
"""
import sys
import argparse

import requests
import upnpclient
from datetime import datetime
from lxml import etree


class SamsungTvNotifier(object):
    def __init__(self, ip, port):
        self._ip = ip
        self._port = port

        self._message_id = 0
        self.message_type = 'text/xml'

        self.notify_action = None

    @property
    def message_id(self):
        self._message_id += 1
        return str(self._message_id)

    @staticmethod
    def get_etree_without_root(root_node):
        ret = b''
        for element in root_node:
            ret += etree.tostring(element)
        return ret.decode('utf-8')

    @staticmethod
    def build_sms_notification(sms_text, sender_name, sender_number, receiver_name, receiver_number,
                               receive_dt=datetime.now()):
        root = etree.Element("root")
        etree.SubElement(root, "Category").text = "SMS"
        etree.SubElement(root, "DisplayType").text = "Maximum"

        receive_time = etree.SubElement(root, "ReceiveTime")
        etree.SubElement(receive_time, "Date").text = receive_dt.strftime('%Y-%m-%d')
        etree.SubElement(receive_time, "Time").text = receive_dt.strftime('%H:%M:%S')

        receiver = etree.SubElement(root, "Receiver")
        etree.SubElement(receiver, "Number").text = receiver_number
        etree.SubElement(receiver, "Name").text = receiver_name

        sender = etree.SubElement(root, "Sender")
        etree.SubElement(sender, "Number").text = sender_number
        etree.SubElement(sender, "Name").text = sender_name

        etree.SubElement(root, "Body").text = sms_text
        return SamsungTvNotifier.get_etree_without_root(root)

    @staticmethod
    def build_call_notification(caller_name, caller_number, callee_name, callee_number,
                                call_dt=datetime.now()):
        root = etree.Element("root")
        etree.SubElement(root, "Category").text = "Incoming Call"
        etree.SubElement(root, "DisplayType").text = "Maximum"

        call_time = etree.SubElement(root, "CallTime")
        etree.SubElement(call_time, "Date").text = call_dt.strftime('%Y-%m-%d')
        etree.SubElement(call_time, "Time").text = call_dt.strftime('%H:%M:%S')

        callee = etree.SubElement(root, "Callee")
        etree.SubElement(callee, "Number").text = callee_number
        etree.SubElement(callee, "Name").text = callee_name

        caller = etree.SubElement(root, "Caller")
        etree.SubElement(caller, "Number").text = caller_number
        etree.SubElement(caller, "Name").text = caller_name
        return SamsungTvNotifier.get_etree_without_root(root)

    @staticmethod
    def build_schedule_notification(subject, location, schedule_text,
                                    owner_name, owner_number,
                                    start_dt, end_dt):
        root = etree.Element("root")
        etree.SubElement(root, "Category").text = "Schedule Reminder"
        etree.SubElement(root, "DisplayType").text = "Maximum"

        start_time = etree.SubElement(root, "StartTime")
        etree.SubElement(start_time, "Date").text = start_dt.strftime('%Y-%m-%d')
        etree.SubElement(start_time, "Time").text = start_dt.strftime('%H:%M:%S')

        owner = etree.SubElement(root, "Owner")
        etree.SubElement(owner, "Number").text = owner_number
        etree.SubElement(owner, "Name").text = owner_name

        etree.SubElement(root, "Subject").text = subject

        end_time = etree.SubElement(root, "EndTime")
        etree.SubElement(end_time, "Date").text = end_dt.strftime('%Y-%m-%d')
        etree.SubElement(end_time, "Time").text = end_dt.strftime('%H:%M:%S')

        etree.SubElement(root, "Location").text = location
        etree.SubElement(root, "Body").text = schedule_text

        return SamsungTvNotifier.get_etree_without_root(root)

    def initialize(self):
        messagebox_url = 'http://{addr}:{port}/pmr/PersonalMessageReceiver.xml'.format(
            addr=self._ip, port=self._port
        )

        try:
            device = upnpclient.Device(messagebox_url)
        except requests.exceptions.ConnectTimeout as e:
            raise Exception('Device looks unavailable! msg: {0}'.format(e))

        service = device.service_map.get('MessageBoxService')
        if not service:
            raise Exception('MessageBoxService not found')

        try:
            self.notify_action = service['AddMessage']
        except KeyError:
            raise Exception('Notification action \'AddMessage\' is unavailable')

    def send_notification(self, notification_body):
        if not self.notify_action:
            raise Exception('Initialization was not done? No action available!')

        self.notify_action(MessageID=self.message_id, MessageType=self.message_type,
                           Message=notification_body)


if __name__ == '__main__':
    parser = argparse.ArgumentParser('Samsung TV Notifier')
    parser.add_argument('ip',
                        help='IP address of target Samsung TV')
    parser.add_argument('--port', '-p', default=52235,
                        help='Port of uPnP service')

    args = parser.parse_args()

    notifier = SamsungTvNotifier(args.ip, args.port)

    try:
        notifier.initialize()
    except Exception as e:
        print('Initialization failed! error: {0}'.format(e))
        sys.exit(1)

    body = notifier.build_sms_notification('Hello, I sent you a SMS', 'tuxuser', '1337', 'samsungctl', '123')
    notifier.send_notification(body)
```

**Comment by tomhash2** [comment]
On my UE55MU6172 doesn't work :(

root@HomeAssistant:~/tizen# ./send.py --port 8001 192.168.10.12
Traceback (most recent call last):
  File "./send.py", line 254, in <module>
    ret = notifier.send_notification(body)
  File "./send.py", line 150, in send_notification
    self.notify_service = self._initialize_notification()
  File "./send.py", line 122, in _initialize_notification
    device = upnpclient.Device(messagebox_url)
  File "/usr/local/lib/python3.4/dist-packages/upnpclient/upnp.py", line 107, in __init__
    resp.raise_for_status()
  File "/usr/local/lib/python3.4/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://192.168.10.12:8001/pmr/PersonalMessageReceiver.xml

**Comment by jhanson999** [comment]
Defalt Port:
root@johnsubuntu:~/scripts# python send.py 10.0.0.92
Traceback (most recent call last):
  File "send.py", line 252, in <module>
    ret = notifier.send_notification(body)
  File "send.py", line 148, in send_notification
    self.notify_service = self._initialize_notification()
  File "send.py", line 120, in _initialize_notification
    device = upnpclient.Device(messagebox_url)
  File "/usr/local/lib/python2.7/dist-packages/upnpclient/upnp.py", line 105, in __init__
    headers=self.http_headers
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.0.0.92', port=52235): Max retries exceeded with url: /pmr/PersonalMessageReceiver.xml (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1154009090>: Failed to establish a new connection: [Errno 111] Connection refused',))

Port 8001:
root@johnsubuntu:~/scripts# python send.py --port 8001 10.0.0.92
Traceback (most recent call last):
  File "send.py", line 252, in <module>
    ret = notifier.send_notification(body)
  File "send.py", line 148, in send_notification
    self.notify_service = self._initialize_notification()
  File "send.py", line 120, in _initialize_notification
    device = upnpclient.Device(messagebox_url)
  File "/usr/local/lib/python2.7/dist-packages/upnpclient/upnp.py", line 107, in __init__
    resp.raise_for_status()
  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://10.0.0.92:8001/pmr/PersonalMessageReceiver.xml

Not working for me either.  Model: KS8000

**Comment by whittin3** [comment]
Is this possible? Any progress?

**Comment by cheesecake441** [comment]
Bought a 55" Samsung TV recently and it would be really great to get this working so I can be reminded about stuffs. Please and thank you <3

**Comment by B-malais** [comment]
I got the notification pop up to allow my device on my UN75CU7000FXZA but then I get the same 404 error as @tomhash2. Any updates?
