### ISSUE TITLE
Couldn't run Samsungctl.

### ISSUE THREAD

**Issue by Crazzilyme** [Ape/samsungctl#52]
This error shows up.

` samsungctl --host 192.168.1.2 key KEY_POWER
Traceback (most recent call last):
  File "/home/pi/.local/bin/samsungctl", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/samsungctl/__main__.py", line 92, in main
    config = _read_config()
  File "/home/pi/.local/lib/python2.7/site-packages/samsungctl/__main__.py", line 37, in _read_config
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
`

When commented the FileNotfoundError exception 
New error popped up

```
samsungctl --host 192.168.1.2 key KEY_POWER
Traceback (most recent call last):
  File "/home/pi/.local/bin/samsungctl", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python2.7/site-packages/samsungctl/__main__.py", line 93, in main
    config = _read_config()
  File "/home/pi/.local/lib/python2.7/site-packages/samsungctl/__main__.py", line 46, in _read_config
    with config_file:
UnboundLocalError: local variable 'config_file' referenced before assignment

```
PS:I used pip for installation.

**Comment by Ape** [comment]
Samsungctl requires Python 3.
