### ISSUE TITLE
UE55LS003 don't work

### ISSUE THREAD

**Issue by openmotion** [Ape/samsungctl#67]
hello
i have this message : Error : Connection refused
 when i execute the command : python -m samsungctl -i --host 192.168.1.40 --method websocket --name myremote

is it normal ? my TV (the Frame) is compatible ?
thanks

**Comment by RiRomain** [comment]
Hi,

Can you check if the URL http://192.168.1.40:8001/api/v2/ is available?

**Comment by iondulgheru** [comment]
Also no working on UE48JU640. I am using port 8001 and websockets.
A request at http://[TV_IP]:8001/api/v2/ returns:
```
{
  "id": "uuid:898025cc-1f80-4a04-ada5-4d13ab35054f",
  "name": "[TV] UE48JU6400",
  "version": "2.0.25",
  "device": {
    "type": "Samsung SmartTV",
    "duid": "uuid:898025cc-1f80-4a04-ada5-4d13ab35054f",
    "model": "15_HAWKM_UHD_2D",
    "modelName": "UE48JU6400",
    "description": "Samsung DTV RCR",
    "networkType": "wired",
    "ssid": "",
    "ip": "192.168.83.73",
    "firmwareVersion": "Unknown",
    "name": "[TV] UE48JU6400",
    "id": "uuid:898025cc-1f80-4a04-ada5-4d13ab35054f",
    "udn": "uuid:898025cc-1f80-4a04-ada5-4d13ab35054f",
    "resolution": "1920x1080",
    "countryCode": "RO",
    "msfVersion": "2.0.25",
    "smartHubAgreement": "true",
    "wifiMac": "[MAC]",
    "developerMode": "0",
    "developerIP": ""
  },
  "type": "Samsung SmartTV",
  "uri": "http://[TV_IP]:8001/api/v2/"
}
```

**Comment by ozzyst** [comment]
Hello, I have TV of UE series and I have trouble with it.
Link is aviable 8001/api/v2/ 
Do you have idea?


```
import samsungctl
import time
config = {
    "name": "samsungctl",
    "description": "PC",
    "id": "1",
    "host": "192.168.1.101",
    "port": 8001,
    "method": "legacy",
    "timeout": 5,
}
with samsungctl.Remote(config) as remote:
    remote.control("KEY_MENU")
        
Traceback (most recent call last):
  File "<input>", line 14, in <module>
  File "/home/slosev/PycharmProjects/torrent/venv/lib/python3.6/site-packages/samsungctl/remote.py", line 9, in __init__
    self.remote = RemoteLegacy(config)
  File "/home/slosev/PycharmProjects/torrent/venv/lib/python3.6/site-packages/samsungctl/remote_legacy.py", line 32, in __init__
    self._read_response(True)
  File "/home/slosev/PycharmProjects/torrent/venv/lib/python3.6/site-packages/samsungctl/remote_legacy.py", line 77, in _read_response
    raise exceptions.ConnectionClosed()
samsungctl.exceptions.ConnectionClosed
```

Should I write an ID in the configuration? What is ID?

**Comment by KJ-Waller** [comment]
Was this issue ever fixed? I have the same TV and I'm getting either "BlockingIOError [Errno 115] Operation now in progress" or "ConnectionClosed" error. I've tried both "legacy" and "websocket".
