### ISSUE TITLE
Error with bash and user without home-directory

### ISSUE THREAD

**Issue by Bissel** [Ape/samsungctl#72]
If you start the script with an user without a home directory e.g. apache an error occur:

```
File "/usr/local/lib/python3.5/dist-packages/samsungctl/__main__.py", line 97, in main
    config = _read_config()
File "/usr/local/lib/python3.5/dist-packages/samsungctl/__main__.py", line 31, in _read_config
    directories.append(os.path.join(os.getenv("HOME"), ".config"))
File "/usr/lib/python3.5/posixpath.py", line 89, in join
    genericpath._check_arg_types('join', a, *p)
File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
    (funcname, s.__class__.__name__)) from None 
```

A fix is maybe add a argument ` --noconf`
and a real fix would be check if the user has a home directory

**Comment by Ape** [comment]
@Bissel Thanks for reporting this. Does #73 fix it?

**Comment by Ape** [comment]
Actually, could you also test if #35 alone fixes it, too?

**Comment by MP-Munich** [comment]
@Ape Thanks for fixing this!

#73 works well.

Output with #35 on my Windows 11 23H2 system:
`Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Temp\samsungctl-master - Copy\samsungctl\__main__.py", line 1, in <module>
    import appdirs
ModuleNotFoundError: No module named 'appdirs'`

Could you please merge #73 to master?
