### ISSUE TITLE
PIP version missing README.md resulting in FileNotFoundError

### ISSUE THREAD

**Issue by CHgsd** [Ape/samsungctl#8]
The last couple versions on pypi are missing README.md resulting in the trigger of FileNotFoundError, which is not defined:
```
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 9, in <module>
    load_entry_point('samsungctl===0.3.0-git', 'console_scripts', 'samsungctl')()
  File "build/bdist.linux-x86_64/egg/samsungctl/__main__.py", line 88, in main
  File "build/bdist.linux-x86_64/egg/samsungctl/__main__.py", line 36, in _read_config
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by Ape** [comment]
Which Python version are you using?

**Comment by auchter** [comment]
Not the original poster, but I'm seeing something similar due to README.md missing.

```
$ pip3.4 install --user samsungctl
Collecting samsungctl
  Using cached samsungctl-0.5.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-2lbrscd9/samsungctl/setup.py", line 15, in <module>
        long_description=open("README.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2lbrscd9/samsungctl
```
Looking at the archive on PyPI, it indeed looks like README.md is missing:

```
$ curl https://pypi.python.org/packages/source/s/samsungctl/samsungctl-0.5.0.tar.gz#md5=addd6426712c32baf2f3beb6f03a984c 2>/dev/null | gunzip | tar t
samsungctl-0.5.0/
samsungctl-0.5.0/samsungctl/
samsungctl-0.5.0/samsungctl/__init__.py
samsungctl-0.5.0/samsungctl/__main__.py
samsungctl-0.5.0/samsungctl/interactive.py
samsungctl-0.5.0/samsungctl/remote.py
samsungctl-0.5.0/samsungctl.egg-info/
samsungctl-0.5.0/samsungctl.egg-info/PKG-INFO
samsungctl-0.5.0/samsungctl.egg-info/SOURCES.txt
samsungctl-0.5.0/samsungctl.egg-info/dependency_links.txt
samsungctl-0.5.0/samsungctl.egg-info/entry_points.txt
samsungctl-0.5.0/samsungctl.egg-info/top_level.txt
samsungctl-0.5.0/setup.py
samsungctl-0.5.0/PKG-INFO
samsungctl-0.5.0/setup.cfg
```

**Comment by Ape** [comment]
Thanks for reporting this issue, and sorry for the delay fixing it. Please send a message if this still occurs.

**Comment by onemico** [comment]
Hi Ape, I am having this issue on version 0.6.0, tried both on MacOS and Raspbian. Any assistance, greatly appreciated.

```
samsungctl --host 192.168.1.100 KEY_VOLDOWN
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/samsungctl", line 11, in <module>
    load_entry_point('samsungctl==0.6.0', 'console_scripts', 'samsungctl')()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/samsungctl/__main__.py", line 93, in main
    config = _read_config()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/samsungctl/__main__.py", line 37, in _read_config
    except FileNotFoundError:
NameError: global name 'FileNotFoundError' is not defined
```

**Comment by Ape** [comment]
@onemico Please use Python 3.

**Comment by onemico** [comment]
Thanks that has resolved it, but i now cannot get it to work on default port or the port I know works with Sammote on my phone:

```
samsungctl --host 192.168.1.100 --port 7676 KEY_VOLDOWN
Error: Connection closed!
```

```
samsungctl --host 192.168.1.100 --port 55000 KEY_VOLDOWN
Error: Connection refused
```
