### ISSUE TITLE
v0.3.0 gives errors relating to missing config if not manually created

### ISSUE THREAD

**Issue by CHgsd** [Ape/samsungctl#9]
Once installed the current pip version (0.3.0) as well as the git Master triggers an undefined error if the config is not manually created.
```
$ samsungctl
Traceback (most recent call last):
  File "/usr/local/bin/samsungctl", line 9, in <module>
    load_entry_point('samsungctl===0.3.0-git', 'console_scripts', 'samsungctl')()
  File "build/bdist.linux-x86_64/egg/samsungctl/__main__.py", line 88, in main
  File "build/bdist.linux-x86_64/egg/samsungctl/__main__.py", line 36, in _read_config
NameError: global name 'FileNotFoundError' is not defined
```
Once the config file is created, this particular error disappears.

**Comment by Ape** [comment]
This should be working with Python 3. Please report if it still occurs.
